### ISSUE TITLE
Plugin does not work: llm-ls process creation fails

### ISSUE THREAD

**Issue by lienharc** [huggingface/llm-intellij#8]
System: Arch Linux
Processor: Intel® Core™ i7-1270P
Intellij Version: IntelliJ IDEA 2023.2.4 (Ultimate Edition)

I am trying to use the plugin with a self-hosted instance. I was able to make the [neovim-plugin](https://github.com/huggingface/llm.nvim) work on my computer, but the one for intellij does not do anything (using the same llm-ls binary).

Intellij logs the following error right after startup which might be related:
```
2023-10-27 16:00:51,173 [ 133942]   WARN - #c.i.e.p.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: /home/tng/.cache/llm_intellij/bin/llm-ls-amd64-unknown-linux-gnu-0.4.0 --stdio
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:35)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:95)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.java:19)
	at com.intellij.platform.lsp.impl.LspServerImpl.q(LspServerImpl.java:377)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by McPatate** [comment]
I see no reason why it wouldn't work with intellij if you've managed to get it to work with neovim. The error isn't really informative either.
Have you tried checking the logs in `~/.cache/llm_ls/llm-ls.log`? If you don't see anything, you'll need to set `llm-ls > Log Level` to info.
Could you screenshot / paste your configuration settings here as well?

**Comment by koljamaier** [comment]
Unfortunately I am facing the same issue. Did not drill to deep yet, but I am also getting `Process hasn't generated any output for a long time.`.
Interesting: When launching IntelliJ I see that the plugin is also firing up successfully (llm-ls server is starting etc.). Sometimes I even get the first code suggestions.
But then after a few seconds/minutes suggestions stop and the error from OP is thrown.
